# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    app.mailer_from: '%env(MAILER_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\AuthEmailService:
        arguments:
            $fromAddress: '%app.mailer_from%'

    App\Service\DatabaseConnection:
        arguments:
            $host: '%env(DB_HOST)%'
            $port: '%env(int:DB_PORT)%'
            $database: '%env(DB_NAME)%'
            $username: '%env(DB_USER)%'
            $password: '%env(DB_PASSWORD)%'

    App\Service\MailjetService:
        arguments:
            $apiKey:    '%env(MAILJET_API_KEY)%'
            $apiSecret: '%env(MAILJET_API_SECRET)%'